### ISSUE TITLE
Support streaming transcoded files from optimized versions server

### ISSUE THREAD

**Issue by MulverineX** [fredrikburmester/streamyfin#157]
**Describe the solution you'd like**
Add streaming support to the optimized versions server and implement in-app.

**Additional context**
This allows for a secondary server to handle transcoding, balancing load and potentially allowing for transcoded streams even if the hardware the Jellyfin server is hosted on isn't powerful enough to support transcoding.

**Comment by FintasticMan** [comment]
I'm quite sure that the optimised versions server still has the JellyFin server do the transcoding, it just then remuxes it into a single file that can be downloaded.

**Comment by MulverineX** [comment]
Nope! It runs ffmpeg off a direct stream of the original file

**Comment by Stetsed** [comment]
Not an actual developer but I did discuss this with  Frederik in the discord on how it would be implemented and what @FintasticMan says is correct. Right now basically all it does is take the stream from jellyfin that was gotten with the device profile, which gives us the m3u8 file and then we use ffmpeg to turn this into a single file.

The transcoding is handled on the jellyfin side if it’s needed, the server just exists to turn it into 1 file due to some issues that where encountered with background downloads(that’s the main reason the optimized server exists), not allowing a bunch of small clips, so it was switched to the current implementation.

I guess what you suggest would be possible, however it would need some reworking and an actual proper implementation of device profiles, but from talking in dev chat that’s on the soonsoonTM list.

**Comment by MulverineX** [comment]
Dang, I guess this suggestion is probably pretty out of scope then, though it's ultimately up to the maintainer. Thanks for the explanation, I should've dug into the code some.
