### ISSUE TITLE
Publish it on FDroid

### ISSUE THREAD

**Issue by 6543** [fredrikburmester/streamyfin#205]
**Describe the solution you'd like**
It would be nice if it's packaged for F-Droid.org

**Additional context**
To be officially packaged, at least an acknoledgement from the upstream project is required ...

**Comment by FintasticMan** [comment]
Unfortunately we won't be able to get Streamyfin to be included in F-Droid's official repositories, because we don't meet the inclusion requirements. We are looking into being added to the IzzyOnDroid repository however.

**Comment by fredrikburmester** [comment]
@FintasticMan what are we missing? Why don't we meet the requirements?

**Comment by FintasticMan** [comment]
All apps published in the official repositories need to be buildable using only fully FLOSS tools, which `eas` is not.

**Comment by fredrikburmester** [comment]
Wow that's crazy, so no eas built react native apps can be on f-droid?

**Comment by 6543** [comment]
I dont know eas but from googling is it an build service?

In that case there must be a way to do so with other building tools?

**Comment by 6543** [comment]
> Wow that's crazy, so no eas built react native apps can be on f-droid?

I like the strict requirement (as user) as it hardens the supply chain (secure apps :))

But Izzy covers the issue too i would say :)

**Comment by qweri0p** [comment]
I'm leaving a comment to clarify the situation for users like me that are wondering what happened.
Streamyfin cannot be put on F-Droid's repository because one of it's build tools isn't FOSS. [(link)](https://f-droid.org/en/docs/Inclusion_Policy/)
Streamyfin cannot be put on IzzyOnDroid because the APK is way too big. [(link)](https://gitlab.com/IzzyOnDroid/repo/-/issues/619)
This issue should probably be closed for now.

**Comment by fredrikburmester** [comment]
I want to conclude this thread by saying that anyone can fork this repo and try to build it following this tutorial: [](https://f-droid.org/2020/10/14/adding-react-native-app-to-f-droid.html) (and also remove chromecast). This might work.

**Comment by Efreak** [comment]
I would like to also note that streamyfin can run their own fdroid repo, and it can even be hosted on GitHub pages, however I'm not sure of the current status of getting fdroid server running in a GitHub action (I stopped hosting my own public repo on GitHub because it was broken for a while; my current repo is privately hosted (on my PC) for my own personal use)

For most users, obtainium should be sufficient.
